### ISSUE TITLE
Create CI/CD

### ISSUE THREAD

**Issue by majkinetor** [OneRemote/docs#1]
Create CI/CD for docs using GH actions and my bundle [mm-docs](https://github.com/majkinetor/mm-docs).

Publish to [GH pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages)

**Comment by majkinetor** [comment]
CI for docs works now and its accessible on 1remote.

I will start working on documentation itself from now on https://1remote.github.io

/cc @VShawn

**Comment by VShawn** [comment]
Let me know if any I can can do to help.
