### ISSUE TITLE
Create multilanguage setup 

### ISSUE THREAD

**Issue by majkinetor** [OneRemote/docs#2]
mkdocs-material [supports language selector](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector).

I know @VShawn that you like that, so I can add it for you.

My personal opinion is to not get involved into that, and just use English.  I definitely don't want to create Serbian docs. App translation is OK on the other hand, because it doesn't require that much work. 

Creating and maintaining technical docs on the other hand is hard and continuous work, while we do this for fun and no profit. Browsers do automatic translate which is really good nowdays, and you can't really make all different language docs follow the same quality and completeness. 

But if you really want it, I will add Chinese for you. Just let me know.

**Comment by VShawn** [comment]
> I know @VShawn that you like that

you misunderstood : ), why my doc has zh-cn version is because I write most doc in my native lang first on IPad in spare time,  then write it to english when I have a PC.

Chinese is not a indispensable option for me. Feel free to create a english only doc.

**Comment by majkinetor** [comment]
Superb. I am glad we are on the same page regarding this. Maintaining a project in a more professional manner is a lot of work even without such distractions.
