### ISSUE TITLE
Any solution for none docker user?

### ISSUE THREAD

**Issue by VShawn** [OneRemote/docs#3]
I can not install docker on my dev computer, is there any solution for me to build it without docker?

**Comment by VShawn** [comment]
done by install python env.

**Comment by majkinetor** [comment]
Sorry, didn't see this.

You can install by hand but docker image includes bunch of other stuff that are very hard to maintain on your own. I keep it updated for more then 4 years now. It is particularly problematic to get [PDF output](https://1remote.org/docs.pdf) or do link automatic testing without it.

**Comment by majkinetor** [comment]
So, what is the problem with docker? I updated to latest mm-docs which I released few days ago, which contains latest mkdocs and material and everything, so I guess if you used python you will have to do that too (not sure).

Docker should be simple as `choco install docker-windows`? Is it the firewall thing? I find that very hard to beleive...

**Comment by VShawn** [comment]
This issue is unrelated to mm-docs. It's because VMware is installed on my PC, so I cannot use Docker (because it based on HyperV). And I am not goning to rebuild my system environment.

**Comment by majkinetor** [comment]
If you have any way to run Linux on your PC, then you can do it. You could see if nested virtualization is enabled for example (as WSL2 is also not an option as it requires HyperV in the backgraound, but WSL1 might be as it doesn't use it)
